apiVersion: v1
kind: ReplicationController
metadata:
  name: git2consul
  labels:
    app: git2consul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: git2consul
    spec:
      containers:
      - name: git2consul
        image: sroskelley/docker-git2consul:latest
        env:
        - name: CFG
          value: '{"version":"1.0","repos":[{"name":"config","url":"https://github.com/valentintodorov/configs.git","branches":["master"],"include_branch_name":false,"ignore_repo_name":true,"ignore_file_extension":true,"expand_keys":true,"hooks":[{"type":"polling","interval":"1"}]}]}'
        - name: CONSUL_ENDPOINT
          value: "10.1.0.251"
        - name: CONSUL_PORT
          value: "8500"
